/**
 * Circuit geometry, DRS zones, corner turns, and authentic lap durations
 * Provides realistic benchmark lap times (in seconds) matching official FIA records.
 */

export const DEFAULT_DRIVERS = [
  { id: 'norris',      code: 'NOR', name: 'Lando Norris',          number: 4,  team: 'McLaren',        color: '#FF8000', photo: '/images/drivers/lando_norris.jpg' },
  { id: 'verstappen',  code: 'VER', name: 'Max Verstappen',        number: 1,  team: 'Red Bull',       color: '#3671C6', photo: '/images/drivers/max_verstappen.webp' },
  { id: 'leclerc',     code: 'LEC', name: 'Charles Leclerc',       number: 16, team: 'Ferrari',        color: '#E8002D', photo: '/images/drivers/charles_leclerc.jpg' },
  { id: 'hamilton',    code: 'HAM', name: 'Lewis Hamilton',        number: 44, team: 'Ferrari',        color: '#E8002D', photo: '/images/drivers/lewis_hamilton.jpg' },
  { id: 'russell',     code: 'RUS', name: 'George Russell',        number: 63, team: 'Mercedes',       color: '#27F4D2', photo: '/images/drivers/george_russell.jpg' },
  { id: 'piastri',     code: 'PIA', name: 'Oscar Piastri',         number: 81, team: 'McLaren',        color: '#FF8000', photo: '/images/drivers/oscar_piastri.jpg' },
  { id: 'antonelli',   code: 'ANT', name: 'Andrea Kimi Antonelli', number: 12, team: 'Mercedes',       color: '#27F4D2', photo: '/images/drivers/kimi_antonelli.jpg' },
  { id: 'alonso',      code: 'ALO', name: 'Fernando Alonso',       number: 14, team: 'Aston Martin',   color: '#229971', photo: '/images/drivers/fernando_alonso.jpg' },
  { id: 'sainz',       code: 'SAI', name: 'Carlos Sainz',          number: 55, team: 'Williams',       color: '#64C4FF', photo: '/images/drivers/carlos_sainz.jpg' },
  { id: 'albon',       code: 'ALB', name: 'Alexander Albon',       number: 23, team: 'Williams',       color: '#64C4FF', photo: '/images/drivers/alex_albon.jpg' },
  { id: 'lawson',      code: 'LAW', name: 'Liam Lawson',           number: 30, team: 'Red Bull',       color: '#3671C6', photo: '/images/drivers/liam_lawson.jpg' },
  { id: 'gasly',       code: 'GAS', name: 'Pierre Gasly',          number: 10, team: 'Alpine',         color: '#0093CC', photo: '/images/drivers/pierre_gasly.png' },
  { id: 'doohan',      code: 'DOO', name: 'Jack Doohan',           number: 7,  team: 'Alpine',         color: '#0093CC', photo: '/images/drivers/pierre_gasly.png' },
  { id: 'tsunoda',     code: 'TSU', name: 'Yuki Tsunoda',          number: 22, team: 'RB',             color: '#6692FF', photo: '/images/drivers/yuki_tsunoda.jpg' },
  { id: 'hadjar',      code: 'HAD', name: 'Isack Hadjar',          number: 6,  team: 'RB',             color: '#6692FF', photo: '/images/drivers/isack_hadjar.jpg' },
  { id: 'bearman',     code: 'BEA', name: 'Oliver Bearman',        number: 87, team: 'Haas',           color: '#B6BABD', photo: '/images/drivers/oliver_bearman.jpg' },
  { id: 'ocon',        code: 'OCO', name: 'Esteban Ocon',          number: 31, team: 'Haas',           color: '#B6BABD', photo: '/images/drivers/esteban_ocon.jpg' },
  { id: 'hulkenberg',  code: 'HUL', name: 'Nico Hülkenberg',       number: 27, team: 'Kick Sauber',    color: '#52E252', photo: '/images/drivers/nico_hulkenberg.jpg' },
  { id: 'bortoleto',   code: 'BOR', name: 'Gabriel Bortoleto',     number: 5,  team: 'Kick Sauber',    color: '#52E252', photo: '/images/drivers/gabriel_bortoleto.jpg' },
  { id: 'stroll',      code: 'STR', name: 'Lance Stroll',          number: 18, team: 'Aston Martin',   color: '#229971', photo: '/images/drivers/lance_stroll.jpg' },
];
export const CIRCUIT_DETAILS = {
  silverstone: {
    name: 'Silverstone Circuit',
    file: 'silverstone',
    country: 'United Kingdom',
    flag: '🇬🇧',
    totalLaps: 52,
    lapDistanceKm: 5.891,
    averageLapTimeSec: 89.2,
    turnsCount: 18,
    reversePath: false,
    turnMilestones: [
      { turn: 1, pos: 0.10 },
      { turn: 3, pos: 0.22 },
      { turn: 6, pos: 0.38 },
      { turn: 9, pos: 0.52 },
      { turn: 11, pos: 0.65 },
      { turn: 15, pos: 0.82 },
      { turn: 18, pos: 0.94 },
    ],
  },
  Zandvoort: {
    name: 'Circuit Zandvoort',
    file: 'Zandvoort',
    country: 'Netherlands',
    flag: '🇳🇱',
    totalLaps: 72,
    lapDistanceKm: 4.259,
    averageLapTimeSec: 72.8,
    turnsCount: 14,
    reversePath: true, // SVG spline drawn counter-clockwise -> reverse so cars travel forward
    turnMilestones: [
      { turn: 1, pos: 0.12 },
      { turn: 3, pos: 0.28 },
      { turn: 7, pos: 0.52 },
      { turn: 10, pos: 0.72 },
      { turn: 14, pos: 0.94 },
    ],
  },
  monza: {
    name: 'Autodromo Nazionale Monza',
    file: 'monza',
    country: 'Italy',
    flag: '🇮🇹',
    totalLaps: 53,
    lapDistanceKm: 5.793,
    averageLapTimeSec: 81.5,
    turnsCount: 11,
    reversePath: false,
    turnMilestones: [
      { turn: 1, pos: 0.16 },
      { turn: 4, pos: 0.38 },
      { turn: 6, pos: 0.52 },
      { turn: 8, pos: 0.72 },
      { turn: 11, pos: 0.92 },
    ],
  },
  Spa: {
    name: 'Circuit de Spa-Francorchamps',
    file: 'Spa',
    country: 'Belgium',
    flag: '🇧🇪',
    totalLaps: 44,
    lapDistanceKm: 7.004,
    averageLapTimeSec: 106.5,
    turnsCount: 19,
    reversePath: false,
    turnMilestones: [
      { turn: 1, pos: 0.08 },
      { turn: 3, pos: 0.18 },
      { turn: 5, pos: 0.36 },
      { turn: 8, pos: 0.48 },
      { turn: 12, pos: 0.68 },
      { turn: 15, pos: 0.82 },
      { turn: 18, pos: 0.92 },
    ],
  },
  monaco: {
    name: 'Circuit de Monaco',
    file: 'monaco',
    country: 'Monaco',
    flag: '🇲🇨',
    totalLaps: 78,
    lapDistanceKm: 3.337,
    averageLapTimeSec: 74.5,
    turnsCount: 19,
    reversePath: false,
    turnMilestones: [
      { turn: 1, pos: 0.12 },
      { turn: 3, pos: 0.25 },
      { turn: 6, pos: 0.42 },
      { turn: 10, pos: 0.62 },
      { turn: 12, pos: 0.75 },
      { turn: 15, pos: 0.86 },
      { turn: 19, pos: 0.96 },
    ],
  },
  bahrain: {
    name: 'Bahrain International Circuit',
    file: 'bahrain',
    country: 'Bahrain',
    flag: '🇧🇭',
    totalLaps: 57,
    lapDistanceKm: 5.412,
    averageLapTimeSec: 93.0,
    turnsCount: 15,
    reversePath: false,
    turnMilestones: [
      { turn: 1, pos: 0.17 },
      { turn: 2, pos: 0.20 },
      { turn: 3, pos: 0.23 },
      { turn: 4, pos: 0.31 },
      { turn: 5, pos: 0.36 },
      { turn: 6, pos: 0.39 },
      { turn: 7, pos: 0.43 },
      { turn: 8, pos: 0.49 },
      { turn: 9, pos: 0.56 },
      { turn: 10, pos: 0.60 },
      { turn: 11, pos: 0.68 },
      { turn: 12, pos: 0.74 },
      { turn: 13, pos: 0.79 },
      { turn: 14, pos: 0.86 },
      { turn: 15, pos: 0.90 },
    ],
  },
  Jeddah: {
    name: 'Jeddah Corniche Circuit',
    file: 'Jeddah',
    country: 'Saudi Arabia',
    flag: '🇸🇦',
    totalLaps: 50,
    lapDistanceKm: 6.174,
    averageLapTimeSec: 90.5,
    turnsCount: 27,
    reversePath: true,
    turnMilestones: [
      { turn: 1, pos: 0.08 },
      { turn: 2, pos: 0.11 },
      { turn: 4, pos: 0.18 },
      { turn: 8, pos: 0.30 },
      { turn: 13, pos: 0.48 },
      { turn: 16, pos: 0.58 },
      { turn: 22, pos: 0.76 },
      { turn: 27, pos: 0.94 },
    ],
  },
  AlbertPark: {
    name: 'Albert Park Circuit',
    file: 'AlbertPark',
    country: 'Australia',
    flag: '🇦🇺',
    totalLaps: 58,
    lapDistanceKm: 5.278,
    averageLapTimeSec: 79.5,
    turnsCount: 14,
    reversePath: false,
    turnMilestones: [
      { turn: 1, pos: 0.14 },
      { turn: 2, pos: 0.18 },
      { turn: 3, pos: 0.26 },
      { turn: 4, pos: 0.30 },
      { turn: 5, pos: 0.37 },
      { turn: 6, pos: 0.44 },
      { turn: 7, pos: 0.48 },
      { turn: 8, pos: 0.53 },
      { turn: 9, pos: 0.62 },
      { turn: 10, pos: 0.66 },
      { turn: 11, pos: 0.76 },
      { turn: 12, pos: 0.81 },
      { turn: 13, pos: 0.88 },
      { turn: 14, pos: 0.93 },
    ],
  },
  Suzuka: {
    name: 'Suzuka International Racing Course',
    file: 'Suzuka',
    country: 'Japan',
    flag: '🇯🇵',
    totalLaps: 53,
    lapDistanceKm: 5.807,
    averageLapTimeSec: 91.5,
    turnsCount: 18,
    reversePath: false,
    turnMilestones: [
      { turn: 1, pos: 0.12 },
      { turn: 2, pos: 0.16 },
      { turn: 3, pos: 0.22 },
      { turn: 7, pos: 0.42 },
      { turn: 8, pos: 0.47 },
      { turn: 11, pos: 0.60 },
      { turn: 13, pos: 0.72 },
      { turn: 15, pos: 0.82 },
      { turn: 16, pos: 0.90 },
    ],
  },
  Shanghai: {
    name: 'Shanghai International Circuit',
    file: 'Shanghai',
    country: 'China',
    flag: '🇨🇳',
    totalLaps: 56,
    lapDistanceKm: 5.451,
    averageLapTimeSec: 95.0,
    turnsCount: 16,
    reversePath: false,
    turnMilestones: [
      { turn: 1, pos: 0.14 },
      { turn: 6, pos: 0.38 },
      { turn: 9, pos: 0.52 },
      { turn: 13, pos: 0.68 },
      { turn: 14, pos: 0.89 },
      { turn: 16, pos: 0.96 },
    ],
  },
  Miami: {
    name: 'Miami International Autodrome',
    file: 'Miami',
    country: 'USA',
    flag: '🇺🇸',
    totalLaps: 57,
    lapDistanceKm: 5.412,
    averageLapTimeSec: 90.0,
    turnsCount: 19,
    reversePath: true,
    turnMilestones: [
      { turn: 1, pos: 0.12 },
      { turn: 7, pos: 0.38 },
      { turn: 11, pos: 0.58 },
      { turn: 14, pos: 0.72 },
      { turn: 17, pos: 0.90 },
    ],
  },
  Imola: {
    name: 'Autodromo Enzo e Dino Ferrari',
    file: 'Imola',
    country: 'Italy',
    flag: '🇮🇹',
    totalLaps: 63,
    lapDistanceKm: 4.909,
    averageLapTimeSec: 77.0,
    turnsCount: 19,
    reversePath: true,
    turnMilestones: [
      { turn: 2, pos: 0.18 },
      { turn: 5, pos: 0.35 },
      { turn: 9, pos: 0.52 },
      { turn: 12, pos: 0.68 },
      { turn: 15, pos: 0.82 },
      { turn: 18, pos: 0.94 },
    ],
  },
  GillesVilleneuve: {
    name: 'Circuit Gilles-Villeneuve',
    file: 'GillesVilleneuve',
    country: 'Canada',
    flag: '🇨🇦',
    totalLaps: 70,
    lapDistanceKm: 4.361,
    averageLapTimeSec: 74.0,
    turnsCount: 14,
    reversePath: false,
    turnMilestones: [
      { turn: 1, pos: 0.14 },
      { turn: 6, pos: 0.40 },
      { turn: 8, pos: 0.55 },
      { turn: 10, pos: 0.68 },
      { turn: 13, pos: 0.92 },
    ],
  },
  Catalunya: {
    name: 'Circuit de Barcelona-Catalunya',
    file: 'Catalunya',
    country: 'Spain',
    flag: '🇪🇸',
    totalLaps: 66,
    lapDistanceKm: 4.657,
    averageLapTimeSec: 76.5,
    turnsCount: 14,
    reversePath: false,
    turnMilestones: [
      { turn: 1, pos: 0.15 },
      { turn: 4, pos: 0.35 },
      { turn: 7, pos: 0.50 },
      { turn: 10, pos: 0.72 },
      { turn: 14, pos: 0.94 },
    ],
  },
  austria: {
    name: 'Red Bull Ring',
    file: 'austria',
    country: 'Austria',
    flag: '🇦🇹',
    totalLaps: 71,
    lapDistanceKm: 4.318,
    averageLapTimeSec: 67.5,
    turnsCount: 10,
    reversePath: false,
    turnMilestones: [
      { turn: 1, pos: 0.15 },
      { turn: 3, pos: 0.38 },
      { turn: 4, pos: 0.54 },
      { turn: 6, pos: 0.68 },
      { turn: 9, pos: 0.88 },
      { turn: 10, pos: 0.95 },
    ],
  },
  hungaroring: {
    name: 'Hungaroring',
    file: 'hungaroring',
    country: 'Hungary',
    flag: '🇭🇺',
    totalLaps: 70,
    lapDistanceKm: 4.381,
    averageLapTimeSec: 78.0,
    turnsCount: 14,
    reversePath: false,
    turnMilestones: [
      { turn: 1, pos: 0.16 },
      { turn: 4, pos: 0.36 },
      { turn: 8, pos: 0.58 },
      { turn: 12, pos: 0.82 },
      { turn: 14, pos: 0.94 },
    ],
  },
  baku: {
    name: 'Baku City Circuit',
    file: 'baku',
    country: 'Azerbaijan',
    flag: '🇦🇿',
    totalLaps: 51,
    lapDistanceKm: 6.003,
    averageLapTimeSec: 104.0,
    turnsCount: 20,
    reversePath: true,
    turnMilestones: [
      { turn: 1, pos: 0.18 },
      { turn: 5, pos: 0.38 },
      { turn: 8, pos: 0.55 },
      { turn: 15, pos: 0.78 },
      { turn: 20, pos: 0.96 },
    ],
  },
  marinabay: {
    name: 'Marina Bay Street Circuit',
    file: 'marinabay',
    country: 'Singapore',
    flag: '🇸🇬',
    totalLaps: 62,
    lapDistanceKm: 4.940,
    averageLapTimeSec: 96.0,
    turnsCount: 19,
    reversePath: true,
    turnMilestones: [
      { turn: 1, pos: 0.12 },
      { turn: 5, pos: 0.32 },
      { turn: 9, pos: 0.52 },
      { turn: 14, pos: 0.74 },
      { turn: 19, pos: 0.95 },
    ],
  },
  Americas: {
    name: 'Circuit of the Americas',
    file: 'Americas',
    country: 'USA',
    flag: '🇺🇸',
    totalLaps: 56,
    lapDistanceKm: 5.513,
    averageLapTimeSec: 97.0,
    turnsCount: 20,
    reversePath: true,
    turnMilestones: [
      { turn: 1, pos: 0.14 },
      { turn: 6, pos: 0.38 },
      { turn: 11, pos: 0.58 },
      { turn: 15, pos: 0.76 },
      { turn: 20, pos: 0.94 },
    ],
  },
  HermanosRodriguez: {
    name: 'Autódromo Hermanos Rodríguez',
    file: 'HermanosRodriguez',
    country: 'Mexico',
    flag: '🇲🇽',
    totalLaps: 71,
    lapDistanceKm: 4.304,
    averageLapTimeSec: 79.5,
    turnsCount: 17,
    reversePath: false,
    turnMilestones: [
      { turn: 1, pos: 0.18 },
      { turn: 4, pos: 0.38 },
      { turn: 7, pos: 0.54 },
      { turn: 12, pos: 0.78 },
      { turn: 17, pos: 0.94 },
    ],
  },
  Interlagos: {
    name: 'Autódromo José Carlos Pace (Interlagos)',
    file: 'Interlagos',
    country: 'Brazil',
    flag: '🇧🇷',
    totalLaps: 71,
    lapDistanceKm: 4.309,
    averageLapTimeSec: 71.5,
    turnsCount: 15,
    reversePath: true,
    turnMilestones: [
      { turn: 1, pos: 0.16 },
      { turn: 4, pos: 0.36 },
      { turn: 8, pos: 0.58 },
      { turn: 12, pos: 0.78 },
      { turn: 15, pos: 0.94 },
    ],
  },
  LasVegas: {
    name: 'Las Vegas Strip Circuit',
    file: 'LasVegas',
    country: 'USA',
    flag: '🇺🇸',
    totalLaps: 50,
    lapDistanceKm: 6.201,
    averageLapTimeSec: 94.5,
    turnsCount: 17,
    reversePath: true,
    turnMilestones: [
      { turn: 1, pos: 0.14 },
      { turn: 5, pos: 0.35 },
      { turn: 12, pos: 0.62 },
      { turn: 14, pos: 0.88 },
      { turn: 17, pos: 0.96 },
    ],
  },
  Lusail: {
    name: 'Lusail International Circuit',
    file: 'Lusail',
    country: 'Qatar',
    flag: '🇶🇦',
    totalLaps: 57,
    lapDistanceKm: 5.419,
    averageLapTimeSec: 84.0,
    turnsCount: 16,
    reversePath: false,
    turnMilestones: [
      { turn: 1, pos: 0.16 },
      { turn: 6, pos: 0.42 },
      { turn: 10, pos: 0.64 },
      { turn: 14, pos: 0.84 },
      { turn: 16, pos: 0.94 },
    ],
  },
  AbuDhabi: {
    name: 'Yas Marina Circuit',
    file: 'AbuDhabi',
    country: 'UAE',
    flag: '🇦🇪',
    totalLaps: 58,
    lapDistanceKm: 5.281,
    averageLapTimeSec: 87.0,
    turnsCount: 16,
    reversePath: false,
    turnMilestones: [
      { turn: 1, pos: 0.12 },
      { turn: 5, pos: 0.28 },
      { turn: 6, pos: 0.48 },
      { turn: 9, pos: 0.68 },
      { turn: 12, pos: 0.82 },
      { turn: 16, pos: 0.95 },
    ],
  },
};

/**
 * Get circuit details with intelligent lookup fallback
 */
export function getCircuitDetails(circuitKey) {
  if (!circuitKey) return CIRCUIT_DETAILS.Zandvoort;
  
  const lower = circuitKey.toLowerCase();
  for (const [key, details] of Object.entries(CIRCUIT_DETAILS)) {
    if (
      key.toLowerCase() === lower ||
      details.file.toLowerCase() === lower ||
      details.name.toLowerCase().includes(lower) ||
      details.country.toLowerCase().includes(lower)
    ) {
      return details;
    }
  }

  return {
    name: circuitKey,
    file: circuitKey,
    country: 'Formula 1',
    flag: '🏁',
    totalLaps: 55,
    lapDistanceKm: 5.3,
    averageLapTimeSec: 88.0,
    turnsCount: 14,
    drsZones: [
      { start: 0.04, end: 0.18, label: 'DRS 1' },
      { start: 0.52, end: 0.68, label: 'DRS 2' },
    ],
    turnMilestones: [
      { turn: 1, pos: 0.15 },
      { turn: 4, pos: 0.35 },
      { turn: 8, pos: 0.60 },
      { turn: 11, pos: 0.78 },
      { turn: 14, pos: 0.94 },
    ],
  };
}
